"""Local Markdown -> HTML renderer using cmark-gfm — GitHub's own renderer.

`cmarkgfm` wraps cmark-gfm, the C library GitHub parses Markdown with, so comment
bodies render byte-identical to GitHub (tables, strikethrough, task lists, autolinks,
footnotes). It's local (no network, no rate limit, no token), fast (C), and we cache
the rendered HTML in the store, so this runs once per add/edit.

XSS-safe by default: we never pass CMARK_OPT_UNSAFE, so raw HTML in a comment is
dropped ("<!-- raw HTML omitted -->") and dangerous link/image schemes (javascript:,
data:, ...) are neutralized to an empty href. No separate sanitizer needed.

Options: HARDBREAKS (a single newline becomes <br>, like GitHub comment bodies) and
FOOTNOTES. NOT enabled: GitHub's app-layer extras (@mentions, #issue refs, :emoji:)
aren't part of cmark-gfm.

Syntax highlighting: cmark-gfm only emits ``<pre lang="X"><code>`` (it doesn't tokenize,
exactly like GitHub's raw renderer — GitHub highlights in a layer on top). We do the same
with Pygments, which emits standard token classes; the Kronuz palette colors them via the
widget's highlight.css (generated by scripts/build-kronuz-themes.mjs from the same palette
as the blog's Shiki themes), so comment code matches the rest of the site.
"""
import html
import re

import cmarkgfm
from cmarkgfm.cmark import Options
from pygments import highlight as _highlight
from pygments.formatters import HtmlFormatter
from pygments.lexers import get_lexer_by_name
from pygments.util import ClassNotFound

# Safe options only (no CMARK_OPT_UNSAFE). getattr keeps this resilient across
# cmarkgfm versions if a flag name ever changes.
_OPTS = 0
for _name in ("CMARK_OPT_HARDBREAKS", "CMARK_OPT_FOOTNOTES"):
    _OPTS |= getattr(Options, _name, 0)

# cmark emits ``<pre lang="LANG"><code>ESCAPED</code></pre>`` for a fenced block with an
# info string. The code is HTML-escaped (so a literal ``<`` is ``&lt;``), which makes the
# closing ``</code></pre>`` unambiguous for this non-greedy match.
_CODE_BLOCK = re.compile(r'<pre lang="([^"]+)"><code>(.*?)</code></pre>', re.DOTALL)
# Emit token classes only (no inline styles); colors live in the widget's highlight.css.
_FORMATTER = HtmlFormatter(cssclass="highlight")


def _highlight_block(match: "re.Match") -> str:
    lang = html.unescape(match.group(1)).strip()
    try:
        lexer = get_lexer_by_name(lang, stripnl=False)
    except ClassNotFound:
        return match.group(0)  # unknown language: leave cmark's plain block untouched
    return _highlight(html.unescape(match.group(2)), lexer, _FORMATTER)


def render(text: str) -> str:
    """Render Markdown to sanitized, GitHub-identical HTML, with Pygments-highlighted
    fenced code blocks (matching how GitHub layers highlighting over cmark-gfm)."""
    out = cmarkgfm.github_flavored_markdown_to_html(text or "", options=_OPTS)
    return _CODE_BLOCK.sub(_highlight_block, out)
