################################################################################
# This config file is meant for settings that affect the whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server
# process.


################################################################################
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

name: Kronuz.io
title: Kronuz
owner: Germán Méndez Bravo (Kronuz)
email: german.mb@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  IO
domain: Kronuz.github.io
url: https://Kronuz.github.io
baseurl: "" # the subpath of your site, e.g. /blog
repository: https://github.com/Kronuz
docs_branch: master/docs
twitter_username: germbravo
github_username:  Kronuz
disqus_shortname: kronuz

theme_color_light: "#bfdd97"
theme_color_dark: "#8fc44a"
theme_color_quickstart: "#689137"

logo: "/img/logo-2x.png"
logo_width: 221
logo_height: 251

google_analytics_id: UA-7630729-2
# google_site_verification: google_site_verification_key
# docsearch_name: Kronuz
# docsearch_key: 00000000000000000000000000000000

################################################################################
# Build settings
markdown: kramdown

collections:
  projects:
    permalink: "/:collection/:path/"
    output: true
  posts:
    permalink: "/blog/:year/:month/:day/:title/"
    output: true

defaults:
  - scope:
      path: _projects
      type: projects
    values:
      layout: projects
  - scope:
      path: _posts
      type: posts
    values:
      layout: blog_item
      image: "/img/twitter-card.png"

plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

sass:
  style: compressed

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - icomoon-selection.json
  - readme.md
  - CNAME
