// @ts-check

import starlight from '@astrojs/starlight';
import { defineConfig } from 'astro/config';
import starlightBlog from 'starlight-blog';
import remarkGfm from 'remark-gfm';
import rehypeExternalLinks from 'rehype-external-links';
import remarkD2 from './src/plugins/remark-d2.mjs';
import remarkSnippet from './src/plugins/remark-snippet.mjs';
import remarkAutoImport from './src/plugins/remark-auto-import.mjs';
import kronuzDark from './src/styles/kronuz-dark.json';
import kronuzLight from './src/styles/kronuz-light.json';

import { SITE_DESCRIPTION, SITE_TITLE } from './src/consts';
import { sidebarConfig } from './src/lib/sidebar.mjs';

// https://astro.build/config
export default defineConfig({
	// Canonical URL of the deployed GitHub Pages site.
	site: 'https://kronuz.github.io',
	// GFM tables in .mdx, and external links (http/https) open in a new tab.
	// Internal relative links (/blog/...) and mailto are left alone.
	markdown: {
		remarkPlugins: [remarkGfm, remarkD2, remarkSnippet, remarkAutoImport],
		rehypePlugins: [
			[
				rehypeExternalLinks,
				{ target: '_blank', rel: ['noopener', 'noreferrer'], protocols: ['http', 'https'] },
			],
		],
	},
	integrations: [
		starlight({
			title: SITE_TITLE,
			description: SITE_DESCRIPTION,
			logo: {
				src: './src/assets/logo.png',
				alt: 'Kronuz',
			},
			favicon: '/favicon.ico',
			customCss: ['./src/styles/custom.css'],
			// Code blocks use the Kronuz theme (dark + a light variant in the
			// same spirit), generated by scripts/build-kronuz-themes.mjs.
			expressiveCode: {
				themes: [kronuzDark, kronuzLight],
			},
			social: [
				{ icon: 'github', label: 'GitHub', href: 'https://github.com/Kronuz' },
				{ icon: 'linkedin', label: 'LinkedIn', href: 'https://www.linkedin.com/in/kronuz/' },
				{ icon: 'x.com', label: 'X', href: 'https://twitter.com/germbravo' },
				{ icon: 'stackOverflow', label: 'Stack Overflow', href: 'https://stackoverflow.com/users/167522/kronuz' },
				{ icon: 'email', label: 'Email', href: 'mailto:german.mb@gmail.com' },
			],
			plugins: [
				starlightBlog({
					title: 'Blog',
					// We own the header nav (Blog + Projects) via our ThemeSelect
					// override, so disable the plugin's built-in single "Blog" link.
					navigation: 'none',
					authors: {
						kronuz: {
							name: 'Germán Méndez Bravo',
							title: 'Software Engineer · Python & Systems Infra',
							url: 'https://github.com/Kronuz',
							picture: 'https://github.com/Kronuz.png',
						},
					},
				}),
				// starlight-blog auto-adds an RSS icon to the social links whenever a
				// feed exists. We surface RSS in the header nav and the post CTA
				// instead, so strip it from the social row here. The feed itself and
				// its <link rel="alternate"> head tag stay (rss remains enabled).
				{
					name: 'kz-drop-rss-social',
					hooks: {
						'config:setup'({ config, updateConfig }) {
							updateConfig({
								social: (config.social ?? []).filter((s) => s.icon !== 'rss'),
							});
						},
					},
				},
			],
			// One authoritative menu, defined in src/lib/sidebar.mjs and rendered on
			// every page by the Sidebar override below. This config copy drives the
			// route-derived bits (e.g. pagination) on docs-style pages.
			sidebar: sidebarConfig(),
			components: {
				PageTitle: './src/components/PageTitle.astro',
				MarkdownContent: './src/components/MarkdownContent.astro',
				TableOfContents: './src/components/TableOfContents.astro',
				Footer: './src/components/Footer.astro',
				SiteTitle: './src/components/SiteTitle.astro',
				ThemeSelect: './src/components/ThemeSelect.astro',
				Sidebar: './src/components/Sidebar.astro',
			},
		}),
	],
});
