// @ts-check

import starlight from '@astrojs/starlight';
import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';
import starlightBlog from 'starlight-blog';
import remarkGfm from 'remark-gfm';
import rehypeExternalLinks from 'rehype-external-links';
import remarkD2 from './src/plugins/remark-d2.mjs';
import remarkSnippet from './src/plugins/remark-snippet.mjs';
import remarkSnippetLink from './src/plugins/remark-snippet-link.mjs';
import remarkSoftBlogLinks from './src/plugins/remark-soft-blog-links.mjs';
import { restLangs } from './src/plugins/rest-lang.mjs';
import { pluginRestCurl } from './src/plugins/ec-rest-curl.mjs';
import kronuzDark from './src/styles/kronuz-dark.json';
import kronuzLight from './src/styles/kronuz-light.json';

import { BLOG_POST_COUNT, RECENT_POST_COUNT, SITE_DESCRIPTION, SITE_TITLE } from './src/consts';
import { sidebarConfig } from './src/lib/sidebar.mjs';

import { readdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { join, extname } from 'node:path';

// https://astro.build/config
export default defineConfig({
	// Canonical URL of the deployed GitHub Pages site.
	site: 'https://kronuz.github.io',
	// The all-posts dashboard moved from /all/ to /blog/all/ (to sit beside the
	// projects dashboard at /projects/all/). Keep the old path working.
	redirects: { '/all': '/blog/all' },
	// Let the Vite dev server accept requests coming through a tunnel (ngrok,
	// Cloudflare Tunnel, etc). Vite 7 blocks unknown Host headers by default and
	// replies "Blocked request. This host ... is not allowed"; `allowedHosts: true`
	// turns that check off. Dev-server only -- it has no effect on the build.
	vite: {
		server: {
			allowedHosts: true,
		},
		plugins: [
			// Route starlight-blog's PrevNextLinks.astro (the "Older/Newer posts" list pager
			// on /blog/, and the built-in per-post footer pager) to our own override, so it
			// renders the same .pagination-links > a[rel] structure as every other pager on
			// the site instead of a Starlight LinkCard. The import is relative inside the
			// dependency, so match it by specifier + importer here (no bare-specifier alias).
			{
				name: 'kz-override-prevnextlinks',
				enforce: 'pre',
				resolveId(source, importer) {
					if (importer && importer.includes('starlight-blog') && /\/PrevNextLinks\.astro$/.test(source)) {
						return fileURLToPath(new URL('./src/overrides/PrevNextLinks.astro', import.meta.url));
					}
					return null;
				},
			},
		],
	},
	// GFM tables in .mdx, and external links (http/https) open in a new tab.
	// Internal relative links (/blog/...) and mailto are left alone.
	markdown: {
		remarkPlugins: [remarkGfm, remarkD2, remarkSnippet, remarkSnippetLink, remarkSoftBlogLinks],
		rehypePlugins: [
			[
				rehypeExternalLinks,
				{ target: '_blank', rel: ['noopener', 'noreferrer'], protocols: ['http', 'https'] },
			],
		],
	},
	integrations: [
		// Our own @astrojs/sitemap (Starlight would otherwise inject one with no
		// filter). The filter drops the private /all/ dashboard from the sitemap;
		// the page is also noindex + pagefind:false + unlinked.
		sitemap({ filter: (page) => !/\/all\/?$/.test(page) }),
		starlight({
			title: SITE_TITLE,
			description: SITE_DESCRIPTION,
			logo: {
				src: './src/assets/logo.png',
				alt: 'Kronuz',
			},
			favicon: '/favicon.ico',
			customCss: ['./src/styles/custom.css'],
			// Code blocks use the Kronuz theme (dark + a light variant in the
			// same spirit), generated by scripts/build-kronuz-themes.mjs.
			expressiveCode: {
				themes: [kronuzDark, kronuzLight],
				// Staged goody (shared with the Xapiand docs): a ```rest fence highlights
				// like http, and its copy button yields a runnable curl. No rest fences in
				// the blog yet; pluginRestCurl({ host }) sets the curl base URL when there are.
				shiki: { langs: restLangs },
				plugins: [pluginRestCurl()],
			},
			social: [
				{ icon: 'github', label: 'GitHub', href: 'https://github.com/Kronuz' },
				{ icon: 'linkedin', label: 'LinkedIn', href: 'https://www.linkedin.com/in/kronuz/' },
				{ icon: 'x.com', label: 'X', href: 'https://twitter.com/germbravo' },
				{ icon: 'stackOverflow', label: 'Stack Overflow', href: 'https://stackoverflow.com/users/167522/kronuz' },
				{ icon: 'email', label: 'Email', href: 'mailto:german.mb@gmail.com' },
			],
			plugins: [
				starlightBlog({
					title: 'Blog',
					// We own the header nav (Blog + Projects) via our ThemeSelect
					// override, so disable the plugin's built-in single "Blog" link.
					navigation: 'none',
					// Sidebar "Recent posts" size and /blog/ index page size. Kept in
					// src/consts.ts so the sidebar "View more" link can compute the page
					// that continues after the recent list.
					recentPostCount: RECENT_POST_COUNT,
					postCount: BLOG_POST_COUNT,
					authors: {
						kronuz: {
							name: 'Germán Méndez Bravo',
							title: 'Software Engineer · Python & Systems Infra',
							url: 'https://github.com/Kronuz',
							picture: 'https://github.com/Kronuz.png',
						},
					},
				}),
				// starlight-blog auto-adds an RSS icon to the social links whenever a
				// feed exists. We surface RSS in the header nav and the post CTA
				// instead, so strip it from the social row here. The feed itself and
				// its <link rel="alternate"> head tag stay (rss remains enabled).
				{
					name: 'kz-drop-rss-social',
					hooks: {
						'config:setup'({ config, updateConfig }) {
							updateConfig({
								social: (config.social ?? []).filter((s) => s.icon !== 'rss'),
							});
						},
					},
				},
			],
			// One authoritative menu, defined in src/lib/sidebar.mjs and rendered on
			// every page by the Sidebar override below. This config copy drives the
			// route-derived bits (e.g. pagination) on docs-style pages.
			sidebar: sidebarConfig(),
			// Drop the empty right "On this page" column on heading-less pages (blog
			// index, tag/author lists, project landings) so the blog and projects
			// spaces behave the same. See src/starlightRouteData.ts.
			routeMiddleware: './src/starlightRouteData.ts',
			// "Edit source" points to the GitHub web editor (baseUrl + the page's source
			// path), rendered next to the title by src/components/PageTitle.astro.
			editLink: {
				baseUrl: 'https://github.com/Kronuz/Kronuz.github.io/edit/master/',
			},
			components: {
				PageTitle: './src/components/PageTitle.astro',
				// The edit affordance lives next to the title; suppress Starlight's footer one.
				EditLink: './src/components/EditLink.astro',
				MarkdownContent: './src/components/MarkdownContent.astro',
				TableOfContents: './src/components/TableOfContents.astro',
				Footer: './src/components/Footer.astro',
				SiteTitle: './src/components/SiteTitle.astro',
				ThemeSelect: './src/components/ThemeSelect.astro',
				Sidebar: './src/components/Sidebar.astro',
				SocialIcons: './src/components/SocialIcons.astro',
			},
		}),
		// Brand the GitHub Pages host as "Kronuz.github.io" in the built output's *visible*
		// URLs (nav/body hrefs, the Giscus theme URL, ...). Astro lowercases the host of every
		// generated absolute URL (new URL() normalizes it), so `site` can't carry the capital
		// K; GitHub serves the host case-insensitively, so we rewrite it in the built files.
		// BUT machine-read URLs must stay on the canonical lowercase host: the RSS feed +
		// sitemap (.xml, skipped entirely) and, in HTML, the feed-autodiscovery <link>, <link
		// rel=canonical>, and og:url/twitter:url meta. A mixed-case host there gets rejected by
		// case-sensitive feed readers / TLS host checks (Reeder "couldn't find a feed") or
		// de-duplicated wrong by crawlers. Matching only "//kronuz.github.io" is deliberate: it
		// skips the bare 'kronuz.github.io' literal the Giscus theme compares against
		// location.hostname, which the browser always reports lowercased.
		{
			name: 'kz-brand-host-case',
			hooks: {
				'astro:build:done': async ({ dir, logger }) => {
					// .xml (feed + sitemap) is never branded; HTML is branded, then the machine
					// tags below are restored to the lowercase host.
					const exts = new Set(['.html', '.txt', '.js', '.css', '.json']);
					const needle = '//kronuz.github.io';
					const branded = '//Kronuz.github.io';
					const machineTag =
						/<(?:link|meta)\b[^>]*(?:\brel=["']?(?:canonical|alternate)["']?|type=["']application\/(?:rss|atom)\+xml["']|(?:property|name)=["'](?:og:url|twitter:url)["'])[^>]*>/gi;
					let files = 0;
					const walk = async (d) => {
						for (const ent of await readdir(d, { withFileTypes: true })) {
							const p = join(d, ent.name);
							if (ent.isDirectory()) {
								await walk(p);
							} else if (exts.has(extname(ent.name))) {
								const s = await readFile(p, 'utf8');
								if (!s.includes(needle)) continue;
								let out = s.replaceAll(needle, branded);
								if (extname(ent.name) === '.html') {
									// Keep feed-autodiscovery, canonical, and social URLs on the
									// canonical lowercase host so readers/crawlers accept them.
									out = out.replace(machineTag, (tag) => tag.replaceAll(branded, needle));
								}
								await writeFile(p, out);
								files++;
							}
						}
					};
					await walk(fileURLToPath(dir));
					logger.info(`Branded host casing to Kronuz.github.io in ${files} file(s).`);
				},
			},
		},
	],
});
